# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ai_panel.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLayout,
    QPlainTextEdit, QPushButton, QScrollBar, QSizePolicy,
    QSpacerItem, QSplitter, QWidget)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        if not DockWidget.objectName():
            DockWidget.setObjectName(u"DockWidget")
        DockWidget.resize(274, 458)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.frame = QFrame(self.dockWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setLocale(QLocale(QLocale.Ukrainian, QLocale.Ukraine))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_3 = QGridLayout(self.frame)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setLocale(QLocale(QLocale.Ukrainian, QLocale.Ukraine))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.gridLayout_6 = QGridLayout(self.groupBox_3)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.splitter_14 = QSplitter(self.groupBox_3)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setOrientation(Qt.Orientation.Vertical)
        self.splitter_14.setHandleWidth(0)
        self.splitter_15 = QSplitter(self.splitter_14)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_15.setHandleWidth(0)
        self.pushButton_46 = QPushButton(self.splitter_15)
        self.pushButton_46.setObjectName(u"pushButton_46")
        sizePolicy.setHeightForWidth(self.pushButton_46.sizePolicy().hasHeightForWidth())
        self.pushButton_46.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"icons/plus-small.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_46.setIcon(icon)
        self.pushButton_46.setIconSize(QSize(30, 30))
        self.splitter_15.addWidget(self.pushButton_46)
        self.pushButton_10 = QPushButton(self.splitter_15)
        self.pushButton_10.setObjectName(u"pushButton_10")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy1)
        icon1 = QIcon()
        icon1.addFile(u"icons/eye.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QSize(24, 24))
        self.splitter_15.addWidget(self.pushButton_10)
        self.pen = QPushButton(self.splitter_15)
        self.pen.setObjectName(u"pen")
        sizePolicy.setHeightForWidth(self.pen.sizePolicy().hasHeightForWidth())
        self.pen.setSizePolicy(sizePolicy)
        icon2 = QIcon()
        icon2.addFile(u"icons/pencil.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pen.setIcon(icon2)
        self.pen.setIconSize(QSize(24, 24))
        self.splitter_15.addWidget(self.pen)
        self.pushButton_11 = QPushButton(self.splitter_15)
        self.pushButton_11.setObjectName(u"pushButton_11")
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        icon3 = QIcon()
        icon3.addFile(u"icons/search.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_11.setIcon(icon3)
        self.splitter_15.addWidget(self.pushButton_11)
        self.comboBox_5 = QComboBox(self.splitter_15)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.splitter_15.addWidget(self.comboBox_5)
        self.splitter_14.addWidget(self.splitter_15)
        self.plainTextEdit_6 = QPlainTextEdit(self.splitter_14)
        self.plainTextEdit_6.setObjectName(u"plainTextEdit_6")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.plainTextEdit_6.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_6.setSizePolicy(sizePolicy2)
        self.plainTextEdit_6.setLineWrapMode(QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.plainTextEdit_6.setTabStopDistance(80.000000000000000)
        self.splitter_14.addWidget(self.plainTextEdit_6)

        self.gridLayout_6.addWidget(self.splitter_14, 1, 0, 1, 1)

        self.splitter_16 = QSplitter(self.groupBox_3)
        self.splitter_16.setObjectName(u"splitter_16")
        sizePolicy.setHeightForWidth(self.splitter_16.sizePolicy().hasHeightForWidth())
        self.splitter_16.setSizePolicy(sizePolicy)
        self.splitter_16.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_16.setHandleWidth(0)
        self.pushButton_47 = QPushButton(self.splitter_16)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.splitter_16.addWidget(self.pushButton_47)
        self.pushButton_48 = QPushButton(self.splitter_16)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.splitter_16.addWidget(self.pushButton_48)

        self.gridLayout_6.addWidget(self.splitter_16, 3, 0, 1, 1)

        self.splitter_10 = QSplitter(self.groupBox_3)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_10.setHandleWidth(0)
        self.pushButton_49 = QPushButton(self.splitter_10)
        self.pushButton_49.setObjectName(u"pushButton_49")
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        icon4 = QIcon()
        icon4.addFile(u"icons/layers.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_49.setIcon(icon4)
        self.pushButton_49.setIconSize(QSize(24, 24))
        self.splitter_10.addWidget(self.pushButton_49)
        self.pushButton_50 = QPushButton(self.splitter_10)
        self.pushButton_50.setObjectName(u"pushButton_50")
        sizePolicy.setHeightForWidth(self.pushButton_50.sizePolicy().hasHeightForWidth())
        self.pushButton_50.setSizePolicy(sizePolicy)
        self.pushButton_50.setIcon(icon1)
        self.pushButton_50.setIconSize(QSize(24, 24))
        self.splitter_10.addWidget(self.pushButton_50)
        self.pushButton_51 = QPushButton(self.splitter_10)
        self.pushButton_51.setObjectName(u"pushButton_51")
        sizePolicy.setHeightForWidth(self.pushButton_51.sizePolicy().hasHeightForWidth())
        self.pushButton_51.setSizePolicy(sizePolicy)
        self.pushButton_51.setIcon(icon2)
        self.pushButton_51.setIconSize(QSize(24, 24))
        self.splitter_10.addWidget(self.pushButton_51)

        self.gridLayout_6.addWidget(self.splitter_10, 0, 0, 1, 1)


        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinAndMaxSize)
        self.splitter_25 = QSplitter(self.frame)
        self.splitter_25.setObjectName(u"splitter_25")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.splitter_25.sizePolicy().hasHeightForWidth())
        self.splitter_25.setSizePolicy(sizePolicy3)
        self.splitter_25.setOrientation(Qt.Orientation.Vertical)
        self.splitter_25.setHandleWidth(0)
        self.pushButton_59 = QPushButton(self.splitter_25)
        self.pushButton_59.setObjectName(u"pushButton_59")
        sizePolicy.setHeightForWidth(self.pushButton_59.sizePolicy().hasHeightForWidth())
        self.pushButton_59.setSizePolicy(sizePolicy)
        self.pushButton_59.setIcon(icon)
        self.pushButton_59.setIconSize(QSize(40, 40))
        self.splitter_25.addWidget(self.pushButton_59)
        self.pushButton_18 = QPushButton(self.splitter_25)
        self.pushButton_18.setObjectName(u"pushButton_18")
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.splitter_25.addWidget(self.pushButton_18)

        self.horizontalLayout.addWidget(self.splitter_25)


        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.verticalScrollBar_2 = QScrollBar(self.frame)
        self.verticalScrollBar_2.setObjectName(u"verticalScrollBar_2")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.verticalScrollBar_2.sizePolicy().hasHeightForWidth())
        self.verticalScrollBar_2.setSizePolicy(sizePolicy4)
        self.verticalScrollBar_2.setOrientation(Qt.Orientation.Vertical)

        self.gridLayout_3.addWidget(self.verticalScrollBar_2, 0, 1, 6, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.verticalSpacer_2, 2, 0, 1, 1)


        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)

        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)

        QMetaObject.connectSlotsByName(DockWidget)
    # setupUi

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QCoreApplication.translate("DockWidget", u"DockWidget", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("DockWidget", u"Sceen 1", None))
        self.pushButton_46.setText("")
        self.pushButton_10.setText("")
        self.pen.setText("")
        self.pushButton_11.setText("")
        self.comboBox_5.setItemText(0, QCoreApplication.translate("DockWidget", u"1", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("DockWidget", u"2", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("DockWidget", u"3", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("DockWidget", u"4", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("DockWidget", u"5", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("DockWidget", u"6", None))

        self.pushButton_47.setText(QCoreApplication.translate("DockWidget", u"add obj", None))
        self.pushButton_48.setText(QCoreApplication.translate("DockWidget", u"render", None))
        self.pushButton_49.setText("")
        self.pushButton_50.setText("")
        self.pushButton_51.setText("")
        self.pushButton_59.setText("")
        self.pushButton_18.setText(QCoreApplication.translate("DockWidget", u"all render", None))
    # retranslateUi

