# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ai_panel.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QFontComboBox, QFrame,
    QGridLayout, QLabel, QPushButton, QSizePolicy,
    QSplitter, QWidget)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        if not DockWidget.objectName():
            DockWidget.setObjectName(u"DockWidget")
        DockWidget.resize(420, 675)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame_5 = QFrame(self.dockWidgetContents)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton_31 = QPushButton(self.frame_5)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(50, 220, 271, 31))
        icon = QIcon()
        icon.addFile(u"icons/plus-small.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_31.setIcon(icon)
        self.pushButton_31.setIconSize(QSize(40, 40))
        self.pushButton_14 = QPushButton(self.frame_5)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(300, 600, 75, 27))
        self.frame = QFrame(self.frame_5)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 400, 200))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.splitter_3 = QSplitter(self.frame)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(0, 0, 144, 32))
        self.splitter_3.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_3.setHandleWidth(0)
        self.pushButton_30 = QPushButton(self.splitter_3)
        self.pushButton_30.setObjectName(u"pushButton_30")
        icon1 = QIcon()
        icon1.addFile(u"icons/layers.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_30.setIcon(icon1)
        self.pushButton_30.setIconSize(QSize(24, 24))
        self.splitter_3.addWidget(self.pushButton_30)
        self.pushButton_21 = QPushButton(self.splitter_3)
        self.pushButton_21.setObjectName(u"pushButton_21")
        icon2 = QIcon()
        icon2.addFile(u"icons/eye.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_21.setIcon(icon2)
        self.pushButton_21.setIconSize(QSize(24, 24))
        self.splitter_3.addWidget(self.pushButton_21)
        self.pushButton_27 = QPushButton(self.splitter_3)
        self.pushButton_27.setObjectName(u"pushButton_27")
        icon3 = QIcon()
        icon3.addFile(u"icons/pencil.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_27.setIcon(icon3)
        self.pushButton_27.setIconSize(QSize(24, 24))
        self.splitter_3.addWidget(self.pushButton_27)
        self.colour_2 = QPushButton(self.splitter_3)
        self.colour_2.setObjectName(u"colour_2")
        icon4 = QIcon()
        icon4.addFile(u"icons/palette.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.colour_2.setIcon(icon4)
        self.colour_2.setIconSize(QSize(24, 24))
        self.splitter_3.addWidget(self.colour_2)
        self.splitter = QSplitter(self.frame)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(0, 80, 381, 32))
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.pushButton_22 = QPushButton(self.splitter)
        self.pushButton_22.setObjectName(u"pushButton_22")
        icon5 = QIcon()
        icon5.addFile(u"icons/arrow-turn-left-down.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_22.setIcon(icon5)
        self.pushButton_22.setIconSize(QSize(24, 24))
        self.splitter.addWidget(self.pushButton_22)
        self.pushButton_2 = QPushButton(self.splitter)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QSize(24, 24))
        self.splitter.addWidget(self.pushButton_2)
        self.pen = QPushButton(self.splitter)
        self.pen.setObjectName(u"pen")
        self.pen.setIcon(icon3)
        self.pen.setIconSize(QSize(24, 24))
        self.splitter.addWidget(self.pen)
        self.colour = QPushButton(self.splitter)
        self.colour.setObjectName(u"colour")
        self.colour.setIcon(icon4)
        self.colour.setIconSize(QSize(24, 24))
        self.splitter.addWidget(self.colour)
        self.pushButton_5 = QPushButton(self.splitter)
        self.pushButton_5.setObjectName(u"pushButton_5")
        icon6 = QIcon()
        icon6.addFile(u"icons/search.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_5.setIcon(icon6)
        self.splitter.addWidget(self.pushButton_5)
        self.fontComboBox = QFontComboBox(self.splitter)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.splitter.addWidget(self.fontComboBox)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 0, 71, 21))
        self.splitter_2 = QSplitter(self.frame)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(230, 170, 150, 27))
        self.splitter_2.setOrientation(Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.pushButton_23 = QPushButton(self.splitter_2)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.splitter_2.addWidget(self.pushButton_23)
        self.pushButton_24 = QPushButton(self.splitter_2)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.splitter_2.addWidget(self.pushButton_24)

        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)

        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)

        QMetaObject.connectSlotsByName(DockWidget)
    # setupUi

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(QCoreApplication.translate("DockWidget", u"DockWidget", None))
        self.pushButton_31.setText("")
        self.pushButton_14.setText(QCoreApplication.translate("DockWidget", u"all render", None))
        self.pushButton_30.setText("")
        self.pushButton_21.setText("")
        self.pushButton_27.setText("")
        self.colour_2.setText("")
        self.pushButton_22.setText("")
        self.pushButton_2.setText("")
        self.pen.setText("")
        self.colour.setText("")
        self.pushButton_5.setText("")
        self.label.setText(QCoreApplication.translate("DockWidget", u"Sceen 1", None))
        self.pushButton_23.setText(QCoreApplication.translate("DockWidget", u"add obj", None))
        self.pushButton_24.setText(QCoreApplication.translate("DockWidget", u"render", None))
    # retranslateUi

